# action.yml
name: 'SSH and SCP Setup'
description: 'Executing remote ssh and scp commands'
author: 'James'
inputs:
  host:
    description: 'ssh remote host'
  port:
    description: 'ssh remote port'
    default: 22
  user:
    description: 'ssh user'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  ssh_before:
    description: 'execute commands before SCP'
  scp:
    description: 'scp local and remote'
  ssh_after:
    description: 'execute commands after SCP'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'
  
# name: 'Hello World'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.who-to-greet }}
